[project]
authors = ["user1"]
entry = "main.sw"
license = "Apache-2.0"
name = "swap_contract"

[dependencies]
pepaswap_helpers = { path = "../pepaswap_helpers" }
swap_abi = { path = "../swap_abi" }
token_abi = { path = "../token_abi" }
factory_abi = { path = "../factory_abi" }