[project]
authors = ["Pepa Labs"]
entry = "main.sw"
license = "Apache-2.0"
name = "token_contract"

[dependencies]
token_abi = { path = "../token_abi" }
pepaswap_helpers = { path = "../pepaswap_helpers" }
