[project]
authors = ["user1"]
entry = "main.sw"
license = "Apache-2.0"
name = "factory_contract"

[dependencies]
factory_abi = { path = "../factory_abi" }
pepaswap_helpers = { path = "../pepaswap_helpers" }
swap_abi = { path = "../swap_abi" }